### ISSUE TITLE
UI/FE Home Page Left Navigation Bar

### ISSUE THREAD

**Issue by SamKO32** [dtalton3/wundereats#17]
## Acceptance Criteria
- Navigation bar displayed
- Navigation bar collapses and expands
- Navigation panels route web UI to appropriate place

## Design Reference
![Screen Shot 2021-09-16 at 5.57.42 PM.png](https://images.zenhubusercontent.com/60370db564c94354031c204c/eea42e3b-6910-45ad-944f-80864d596285)

## Notes
Some of the panels in the above design may not be in scope anymore. Assignee(s) need to determine  which ones need to be removed

Depending on what navigation panels remain, we need to decide whether we should make separate tickets for each page, combine some, or do an empty page shell for each one

**Comment by xNickyB** [comment]
Created a new branch for the development of the left navigation bar. Constructed vertical navbar similarly to “Navbar.js” (which represents the horizontal navbar). Added a component "VNavbar" to components folder with similar "vMenuitems.js" and "vNavbar.css" files. Added relevant names of links to “vMenuitems”.js and toyed with “VNavbar.css” until it was in a decent place.
Also added a <div> tag for a corner logo inserted in the top left of the canvas of "Home.js" not sure if needed, but we can always revert. Would've worked better if I could figure out how to resize it well.

I'm currently, having trouble writing dimensions that resize well. Next steps are to make the menu collapsible and fix the resizing of the left panel (And possibly corner logo div, if we decide to use it). We also should determine how many of the vertical navbar links will be in the final MVP. Here's how it currently looks.

![Screen Shot 2021-09-19 at 2.50.36 PM.png](https://images.zenhubusercontent.com/6036e77f54742f036d9fb657/a888e3b2-94bb-4ac7-9129-9d4bb65b1956)
