### ISSUE TITLE
UI/FE Home Page Horizontal Navigation Bar

### ISSUE THREAD

**Issue by xNickyB** [dtalton3/wundereats#19]
## Acceptance Criteria
- Navigation bar should be juxtaposed with the top of the left navigation bar
- Navigation bar should adjust appropriately when left navigation bar is collapsed/expanded
- Should allow links for relevant pages (Home[Dashboard], About us, User Profile)

## Design References
![Screen Shot 2021-09-16 at 6.04.23 PM.png](https://images.zenhubusercontent.com/6036e77f54742f036d9fb657/77a455fb-59fb-4c8b-a045-d016cc3355cd)

## Notes
- logo will eventually be replaced with new branded logo

**Comment by hnguy3n** [comment]
Created a new branch for the development of the top horizontal navigation bar. Made a folder called "components" and another corresponding folder called "Navbars". There are js files for the Navbar with CSS to accompany it according to the picture above. Had some problems with displaying the old image in the top left corner and the nav menu items aren't properly routed yet.
